### ISSUE TITLE
[Discussion] Integrating a static site generator

### ISSUE THREAD

**Issue by avks** [estevanmaito/windmill-dashboard#2]
Hi!
First of all, thank you for this theme. Design- and a11y-wise, it follows the principles Adam Wathan advocates. I personally really love the modal, specially on mobile.

I have forked the repo and started working on adding a static site generator to it. Something like 11ty or hexo, may be. The most significant benefit will be reusing existing html files to make it more modular. I would like to know what @estevanmaito thinks about the idea.

**Comment by estevanmaito** [comment]
Hey! Thank you!

It's a great idea. Personally, I don't see a lot of people using this dashboard as pure HTML but instead implementing some sort of template engine like Handlebars, etc or SSG.

I don't plan to change this project to keep this flexibility, but I encourage you to create a new repo like `windmill-dashboard-hexo` and develop it. Just put a link to the main project and I would proudly start an "Alternatives" section in this repo and point to your project. I think it would be a great start to an ecosystem.

Let me know what you think!

**Comment by avks** [comment]
Yea, sounds good to me. Let me see what I can do. :)
